---
    - name: app setup
      include_role: 
        name: common
        tasks_from: app-setup

    - name: nodejs setup
      include_role: 
        name: common
        tasks_from: nodejs

    - name: copy mongodb repo
      ansible.builtin.copy:
        src: mongodb.repo
        dest: /etc/yum.repos.d/mongodb.repo
    
    - name: Install mongodb client
      ansible.builtin.dnf:
        name: mongodb-mongosh
        state: present

    - name: check if products data is loaded
      ansible.builtin.command: mongosh --host mongodb.rameshaws.site --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
      register: load_products_data
      #ignore_errors: true

    - name: print products data load status
      ansible.builtin.debug:
        msg: "{{ load_products_data }}"
      #ignore_errors: true

    - name: Load products 
      ansible.builtin.shell: mongosh --host mongodb.rameshaws.site < /app/db/master-data.js
      when: load_products_data.stdout | int < 0  
      #ignore_errors: true

    - name: systemd setup
      include_role: 
        name: common
        tasks_from: systemd

    # - name: Deployment using tags
    #   tags:
    #   - deployment
    #   include_role: 
    #     name: common
    #     tasks_from: deployment