---
  - name: stop the service {{ component }}
    ansible.builtin.service:
      name: "{{ component }}"
      state: stopped

  - name: remove /app directory
    ansible.builtin.file:
      state: absent
      path: /app

  - name: create /app directory
    ansible.builtin.file:
      state: directory
      path: /app

  - name: download application
    ansible.builtin.unarchive:
      url: "https://roboshop-artifacts.s3.amazonaws.com/{{ component }}-{{ app_version }}.zip"
      dest: /app
      remote_src: yes

  - name: install dependenceis 
    ansible.builtin.npm:
      path: /app

  - name: restart {{ component }}
    ansible.builtin.service:
      name: "{{ component }}"
      state: restarted

